[package]
name = "nourfetch"
version = "1.0.5"
edition = "2021"
authors = ["Nour <contact@rayane.ma>"]
description = "A fast and lightweight system information tool for Windows, Linux, and macOS"
readme = "README.md"
license = "MIT"
keywords = ["neofetch", "fastfetch", "sysinfo", "cli", "system-information"]
categories = ["command-line-utilities"]

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
