# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: itsraynour.nourfetch
PackageVersion: 1.0.4
InstallerType: portable
Commands:
- nourfetch
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/itsraynour/nourfetch/releases/download/v1.0.4/nourfetch-windows-x86_64.exe
ManifestType: installer
ManifestVersion: 1.12.0
